<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'vich_uploader.namer_base64' shared service.

return $this->services['vich_uploader.namer_base64'] = new \Vich\UploaderBundle\Naming\Base64Namer();
