<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'vich_uploader.namer_directory_property' shared service.

return $this->services['vich_uploader.namer_directory_property'] = new \Vich\UploaderBundle\Naming\PropertyDirectoryNamer(${($_ = isset($this->services['property_accessor']) ? $this->services['property_accessor'] : $this->load(__DIR__.'/getPropertyAccessorService.php')) && false ?: '_'});
