<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSxvpjzd\appTestProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSxvpjzd/appTestProjectContainer.php') {
    touch(__DIR__.'/ContainerSxvpjzd.legacy');

    return;
}

if (!\class_exists(appTestProjectContainer::class, false)) {
    \class_alias(\ContainerSxvpjzd\appTestProjectContainer::class, appTestProjectContainer::class, false);
}

return new \ContainerSxvpjzd\appTestProjectContainer(array(
    'container.build_hash' => 'Sxvpjzd',
    'container.build_id' => 'f06e4188',
    'container.build_time' => 1524061193,
));
