<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ2jptcb\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ2jptcb/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZ2jptcb.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZ2jptcb\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZ2jptcb\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Z2jptcb',
    'container.build_id' => '2ec52d47',
    'container.build_time' => 1524478932,
));
